# Generated by Django 6.0.7 on 2026-10-08 17:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("section", 3), ("cta", 13), ("statistics", 17)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "icon": "title",
                                    "template": "components/streamfield/blocks/heading2_block.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "h3",
                                    ],
                                    "template": "components/streamfield/blocks/paragraph_block.html",
                                },
                            ),
                            2: ("wagtail.blocks.StreamBlock", [[("paragraph", 1)]], {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("content", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "icon": "title",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            6: ("wagtail.blocks.PageChooserBlock", (), {}),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use page's listing title.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 6), ("title", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.URLBlock", (), {}),
                            10: ("wagtail.blocks.CharBlock", (), {}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("link", 9), ("title", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.StreamBlock",
                                [[("internal", 8), ("external", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("text", 5), ("button", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                                    "label": "Screen reader only label",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("utils.Statistic",),
                                {},
                            ),
                            16: (
                                "wagtail.blocks.ListBlock",
                                (15,),
                                {"max_num": 3, "min_num": 3},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 4),
                                        ("sr_only_label", 14),
                                        ("statistics", 16),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Short summary. Shown at the top of the page and on the service cards.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("section", 3), ("cta", 13), ("statistics", 17)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "icon": "title",
                                    "template": "components/streamfield/blocks/heading2_block.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "h3",
                                    ],
                                    "template": "components/streamfield/blocks/paragraph_block.html",
                                },
                            ),
                            2: ("wagtail.blocks.StreamBlock", [[("paragraph", 1)]], {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("content", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "icon": "title",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            6: ("wagtail.blocks.PageChooserBlock", (), {}),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use page's listing title.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 6), ("title", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.URLBlock", (), {}),
                            10: ("wagtail.blocks.CharBlock", (), {}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("link", 9), ("title", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.StreamBlock",
                                [[("internal", 8), ("external", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("text", 5), ("button", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                                    "label": "Screen reader only label",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("utils.Statistic",),
                                {},
                            ),
                            16: (
                                "wagtail.blocks.ListBlock",
                                (15,),
                                {"max_num": 3, "min_num": 3},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 4),
                                        ("sr_only_label", 14),
                                        ("statistics", 16),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
